---
- name: Find out stuff
  hosts: all
  connection: local
  tasks:
    - name: Find the hostname
      debug:
        var: ansible_hostname
    - name: Find myIP
      debug:
        var: ansible_default_ipv4.address
    - name: Copy my file
      copy:
        src: /Users/jhugo/Downloads/slyt441.pdf 
        dest: .
    - name: Put my text in a file
      lineinfile:
        dest: testfile 
        line: "My text"

